const ACTION_TYPES = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_STEP: "SET_STEP",
  CHANGE_LANGUAGES: "CHANGE_LANGUAGES",
  CHANGE_THEME: "CHANGE_THEME",
};

export default ACTION_TYPES;
